server:
  port: 8766

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG


eureka:
  instance:
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:${spring.application.name}
  client:
    registry-fetch-interval-seconds: 10
    lease-renewal-interval-in-seconds: 10
    healthcheck:
      enabled: true
